apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ens1f0-policy 
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: "" 
  maxUnavailable: 3 
  desiredState:
    interfaces:
      - name: ens1f0
        mtu: 9000
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
