apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: pci-sriov-net-ens1f0
  namespace: openshift-sriov-network-operator 
spec:
  resourceName: pci_sriov_net_ens1f0
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true" 
  priority: 10
  mtu: 9000
  needVhostNet: false 
  numVfs: 16
  externallyManaged: false 
  nicSelector: 
    pfNames: ["ens1f0#0-15"]
  deviceType: vfio-pci
  isRdma: false 
  excludeTopology: false 
